#!/bin/bash

# Link standard files to standard places

SRC=~/repos/stdhome
HM=~

# Set CWD
cd ${HM}

# Link dotfiles
ln -s ${SRC}/.[a-z]* .

# Link individual bin files
mkdir -f bin
ln -s ${SRC}/bin/* bin

# Link info folder
mkdir -f info
ln -s ${SRC}/info/* info

